name: Fm mock
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    - name: Install NodeJs
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        node-version: 18
        cache: 'npm'
    - name: Cache NPM dependencies
      uses: actions/cache@v3
      id: cache-primes
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}      
    - name: Install dependencies
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: npm ci
    - name: Run Test
      run: npm run test
    - name: Example Multi
      run: npm run example-multi
    - name: Build
      run: npm run build
    - uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}